import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Image from "next/image";

export const metadata = {
  title: "MentorWeb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header></Header>
      <body className="bg-customPink">{children}</body>
    </html>
  );
}
