
import "./globals.css";
import MentorWebIco from "./MentorWebIco.png";
import Image from "next/image";
import { MiProvider } from './../context/context.js'



export const metadata = {
  title: "MentorWeb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <MiProvider>
      <html lang="en">
        <body className="bg-customPink">
          <header className="bg-white">
            <div className="grid grid-cols-2 p-8  w-1/6">
              <Image src={MentorWebIco} alt="MentorWeb Icon" width={50} height={50} />
              <h1 className="pt-3">MentorWeb</h1> 
            </div>
          </header>
          {children}
        </body>
      </html>
    </MiProvider>
  )
}
